# Generated by Django 3.2 on 2023-06-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Филлиал')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('check_branch', models.BooleanField(default=True, verbose_name='Открыто')),
            ],
            options={
                'verbose_name': 'Филлиал',
                'verbose_name_plural': 'Филлиалы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Номер телефона')),
                ('phone_number2', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Номер телефона2')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CodeGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True, verbose_name='Сгенерированный код')),
                ('discount', models.IntegerField(default=3, verbose_name='Процент скидки')),
                ('regular_customer', models.BooleanField(default=False, verbose_name='Постоянный клиент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации кода')),
                ('confirmed_presence', models.BooleanField(default=False, verbose_name='Подтверждено личное присутствие')),
                ('purchase_privileges', models.BooleanField(default=False, verbose_name='Привилегии при покупке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to='main.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код пользователей',
                'verbose_name_plural': 'Коды пользователей',
            },
        ),
    ]
