# Generated by Django 3.2 on 2023-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230624_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='check_branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default='22:00', verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(default='08:00', verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Филиал'),
        ),
    ]
