# Generated by Django 3.2 on 2023-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230626_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default='21:00', verbose_name='Время закрытия'),
        ),
    ]
