# Generated by Django 3.2 on 2023-06-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_branch_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='codegenerate',
            name='summ',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма товара'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
    ]
