# Generated by Django 3.2 on 2023-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230627_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codegenerate',
            name='discount',
            field=models.IntegerField(default=2, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='discount',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='visits',
            field=models.IntegerField(blank=True, null=True, verbose_name='Посещение'),
        ),
    ]
