# Generated by Django 3.2 on 2023-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230627_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regularuser',
            unique_together={('user',)},
        ),
    ]
