# Generated by Django 3.2 on 2023-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_regularuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(default=1, max_length=50, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
